import type { RequestHandler } from "@cloudflare/workers-types";

const DEFAULT_MODEL = "gemini-1.5-flash-latest";
const DEFAULT_API_URL = (model: string) =>
  `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`;

async function callGeminiImage(apiUrl: string, apiKey: string, prompt: string) {
  const url = `${apiUrl}?key=${encodeURIComponent(apiKey)}`;
  const body = {
    contents: [
      {
        role: "user",
        parts: [{ text: prompt }],
      },
    ],
    generationConfig: {
      // Use JSON output with base64 image field
      responseMimeType: "application/json",
      responseSchema: {
        type: "object",
        properties: {
          base64: { type: "string" },
          mime: { type: "string" },
        },
        required: ["base64"],
      },
      candidateCount: 1,
    },
    safetySettings: [
      { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" },
      { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" },
    ],
  } as const;

  const resp = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!resp.ok) {
    const text = await resp.text();
    throw new Error(`Gemini API ${resp.status}: ${text}`);
  }

  const data = await resp.json();
  const jsonText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!jsonText) {
    throw new Error("Gemini 响应缺少 JSON 文本");
  }
  let parsed: any;
  try {
    parsed = JSON.parse(jsonText);
  } catch (e) {
    throw new Error("Gemini 返回内容无法解析 JSON");
  }
  const base64 = parsed.base64;
  const mime = parsed.mime || "image/png";
  if (!base64) throw new Error("Gemini JSON 未包含 base64 字段");
  return { base64, mime };
}

function buildPrompt(foodName: string) {
  const name = foodName.trim();
  return `You are a Master Food Deconstructionist & Designer. When given a food name, output a JSON with base64 field containing an image (data without prefix) generated by Gemini image ability. Follow this prompt for image generation:
Premium commercial food poster featuring deconstructed layers of ${name} floating in a vertical stack on a pure black background (#000000).
- Massive translucent background text '${name}' in appropriate cultural font at 15% opacity.
- Layers top to bottom: garnish scatter; vivid secondary veg; core protein with texture; base/carb with structure; dynamic sauce splash; transition gap with steam/oil; final plated ${name}.
- Chinese/English thin-line labels; dramatic 45° studio light; rim light; 8k ultra-realistic food photography.
Return JSON: {"base64": "<BASE64_NO_PREFIX>", "mime": "image/png"}.`;
}

export const onRequestPost: RequestHandler = async ({ request, env }) => {
  try {
    const { character_name, food_name, style } = await request.json<any>();
    const name = (food_name || character_name || "").trim();
    if (!name) {
      return new Response(JSON.stringify({ error: "缺少美食名称" }), { status: 400 });
    }

    const apiKey = env.GEMINI_API_KEY;
    if (!apiKey) {
      return new Response(JSON.stringify({ error: "缺少 GEMINI_API_KEY" }), { status: 500 });
    }

    const model = env.AI_MODEL_NAME || DEFAULT_MODEL;
    const apiUrl = env.AI_MODEL_URL || DEFAULT_API_URL(model);

    const prompt = buildPrompt(name);
    const { base64, mime } = await callGeminiImage(apiUrl, apiKey, prompt);
    const imageUrl = `data:${mime};base64,${base64}`;

    return new Response(
      JSON.stringify({ image_url: imageUrl, style: style || "food_poster" }),
      {
        headers: { "Content-Type": "application/json" },
      },
    );
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err?.message || "未知错误" }), { status: 500 });
  }
};